### ISSUE TITLE
Enhancements in Frontend

### ISSUE THREAD

**Issue by The-Naveen** [The-Naveen/NITCONF#21]
All these mentioned need to be completed accordingly:

- [x] update home_page.html to Home.html
- [x] connect to every other page from Home.html
- [x] redirect **NITCONF** logo on every page redirect to Home.html
- [x] In every other page try to add notification icon and profile.
If not possible then make it as consistent as possible
- [x] The-Naveen/NITCONF/issues/18
- [x] The-Naveen/NITCONF/issues/15
- [x] The-Naveen/NITCONF/issues/22
